### GET por idade
GET http://localhost:3000/users/?age=insira_número_da_idade HTTP/1.1
content-type: application/json

### GET por celular
GET http://localhost:3000/user/?cell=insira_número_do_celular HTTP/1.1
content-type: application/json

### GET por ID
GET http://localhost:3000/users/insira_id_do_usuário HTTP/1.1
content-type: application/json

### PATCH por ID
PATCH http://localhost:3000/users/insira_id_do_usuário HTTP/1.1
content-type: application/json

{
	"name":"insira o nome", 
	"cpf": "insira o cpf", 
	"age": "insira idade (inteiro)", 
	"cell": "insira celular (tamanho menor que 11)"
}

### POST
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
	"name":"insira o nome", 
	"cpf": "insira o cpf", 
	"age": "insira idade (inteiro)", 
	"cell": "insira celular (tamanho menor que 11)"
}

### DELETE
DELETE http://localhost:3000/users/id_do_elemento_a_ser_deletado HTTP/1.1
content-type: application/json